<?php
$currency_sql="INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (1, '" . __('Mauritania') ."', 'MR', '" . __('Mauritanian Ouguiya') ."', '', '', " . __('MRO', 'wpsc') . ", '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (2, '" . __('Martinique (French)') ."', 'MQ', '" . __('Euro') ."', " . __('€', 'wpsc') . ", " . __('&#8364;', 'wpsc') . ", " . __('EUR', 'wpsc') . ", '0', '0','southamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (3, '" . __('Malta') ."', 'MT', '" . __('Maltese Lira') ."', '', '', " . __('MTL', 'wpsc') . ", '0', '0' ,'europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (4, '" . __('Marshall Islands') ."', 'MH', '" . __('US Dollar') ."', " . __('$', 'wpsc') . ", " . __('&#036;', 'wpsc') . ", " . __('USD', 'wpsc') . ", '0', '0' ,'asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (5, '" . __('Mali') ."', 'ML', '" . __('CFA Franc BCEAO') ."', '', '', " . __('XOF', 'wpsc') . ", '0', '0' ,'africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (6, '" . __('Maldives') ."', 'MV', '" . __('Maldive Rufiyaa') ."', '', '', " . __('MVR', 'wpsc') . ", '0', '0' , 'asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (7, '" . __('Malaysia') ."', 'MY', '" . __('Malaysian Ringgit') ."', '', '', " . __('MYR', 'wpsc') . ", '0', '0', 'asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (8, '" . __('Malawi') ."', 'MW', '" . __('Malawi Kwacha') ."', '', '', " . __('MWK', 'wpsc') . ", '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (9, '" . __('Madagascar') ."', 'MG', '" . __('Malagasy Franc') ."', '', '', " . __('MGF', 'wpsc') . ", '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (10, '" . __('Macau') ."', 'MO', '" . __('Macau Pataca') ."', '', '', " . __('MOP', 'wpsc') . ", '0', '0', 'asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (11, '" . __('Macedonia') ."', 'MK', '" . __('Denar') ."', '', '', " . __('MKD', 'wpsc') . ", '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (12, '" . __('Luxembourg') ."', 'LU', '" . __('Euro') ."', " . __('€', 'wpsc') . ", " . __('&#8364;', 'wpsc') . ", " . __('EUR', 'wpsc') . ", '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (13, '" . __('Lithuania') ."', 'LT', '" . __('Lithuanian Litas') ."', '', '', " . __('LTL', 'wpsc') . ", '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (14, '" . __('Liechtenstein') ."', 'LI', '" . __('Swiss Franc') ."', '', '', " . __('CHF', 'wpsc') . ", '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (15, '" . __('Libya') ."', 'LY', '" . __('Libyan Dinar') ."', '', '', " . __('LYD', 'wpsc') . ", '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (16, '" . __('Liberia') ."', 'LR', '" . __('Liberian Dollar') ."', " . __('$', 'wpsc') . ", " . __('&#036;', 'wpsc') . ", " . __('LRD', 'wpsc') . ", '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (17, '" . __('Lesotho') ."', 'LS', '" . __('Lesotho Loti') ."', '', '', " . __('LSL', 'wpsc') . ", '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (18, '" . __('Lebanon') ."', 'LB', '" . __('Lebanese Pound') ."', '', '', " . __('LBP', 'wpsc') . ", '0', '0', 'asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (19, '" . __('Latvia') ."', 'LV', '" . __('Latvian Lats') ."', '', '', " . __('LVL', 'wpsc') . ", '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (20, '" . __('Laos') ."', 'LA', '" . __('Lao Kip') ."', '', '', " . __('LAK', 'wpsc') . ", '0', '0', 'asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (21, '" . __('Kyrgyzstan') ."', 'KG', '" . __('Som') ."', '', '', " . __('KGS', 'wpsc') . ", '0', '0', 'asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (22, '" . __('Kuwait') ."', 'KW', '" . __('Kuwaiti Dinar') ."', '', '', " . __('KWD', 'wpsc') . ", '0', '0', 'asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (23, '" . __('Korea, South') ."', 'KR', '" . __('Korean Won') ."', '', '', " . __('KRW', 'wpsc') . ", '0', '0', 'asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (24, '" . __('Korea, North') ."', 'KP', '" . __('North Korean Won') ."', '', '', " . __('KPW', 'wpsc') . ", '0', '0', 'asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (25, '" . __('Kiribati') ."', 'KI', '" . __('Australian Dollar') ."', " . __('$', 'wpsc') . ", " . __('&#036;', 'wpsc') . ", " . __('AUD', 'wpsc') . ", '0', '0', 'asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (26, '" . __('Kenya') ."', 'KE', '" . __('Kenyan Shilling') ."', '', '', " . __('KES', 'wpsc') . ", '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (27, '" . __('Kazakhstan') ."', 'KZ', '" . __('Kazakhstan Tenge') ."', '', '', " . __('KZT', 'wpsc') . ", '0', '0' ,'asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (28, '" . __('Jordan') ."', 'JO', '" . __('Jordanian Dinar') ."', '', '', " . __('JOD', 'wpsc') . ", '0', '0', 'asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (29, '" . __('Jersey') ."', 'JE', '" . __('Pound Sterling') ."', " . __('£', 'wpsc') . ", " . __('&#163;', 'wpsc') . ", " . __('GBP', 'wpsc') . ", '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (30, '" . __('Japan') ."', 'JP', '" . __('Japanese Yen') ."', " . __('¥', 'wpsc') . ", " . __('&#165;', 'wpsc') . ", " . __('JPY', 'wpsc') . ", '0', '0', 'asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (31, '" . __('Jamaica') ."', 'JM', '" . __('Jamaican Dollar') ."', " . __('$', 'wpsc') . ", " . __('&#036;', 'wpsc') . ", " . __('JMD', 'wpsc') . ", '0', '0' ,'southamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (32, '" . __('Ivory Coast') ."', 'CI', '" . __('CFA Franc BCEAO') ."', '', '', " . __('XOF', 'wpsc') . ", '0', '0' ,'africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (33, '" . __('Italy') ."', 'IT', '" . __('Euro') ."', " . __('€', 'wpsc') . ", " . __('&#8364;', 'wpsc') . ", " . __('EUR', 'wpsc') . ", '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (34, '" . __('Isle of Man') ."', 'IM', '" . __('Pound Sterling') ."', " . __('£', 'wpsc') . ", " . __('&#163;', 'wpsc') . ", " . __('GBP', 'wpsc') . ", '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (35, '" . __('Israel') ."', 'IL', '" . __('Israeli New Shekel') ."', '', '', " . __('ILS', 'wpsc') . ", '0', '0',  'asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (36, '" . __('Ireland') ."', 'IE', '" . __('Euro') ."', " . __('€', 'wpsc') . ", " . __('&#8364;', 'wpsc') . ", " . __('EUR', 'wpsc') . ", '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (37, '" . __('Iraq') ."', 'IQ', '" . __('Iraqi Dinar') ."', '', '', " . __('IQD', 'wpsc') . ", '0', '0',  'asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (38, '" . __('Indonesia') ."', 'ID', '" . __('Indonesian Rupiah') ."', '', '', " . __('IDR', 'wpsc') . ", '0', '0',  'asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (39, '" . __('Iran') ."', 'IR', '" . __('Iranian Rial') ."', '', '', " . __('IRR', 'wpsc') . ", '0', '0',  'asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (40, '" . __('India') ."', 'IN', '" . __('Indian Rupee') ."', '', '', " . __('INR', 'wpsc') . ", '0', '0',  'asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (41, '" . __('Iceland') ."', 'IS', '" . __('Iceland Krona') ."', '', '', " . __('ISK', 'wpsc') . ", '0', '0', 'europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (42, '" . __('Hungary') ."', 'HU', '" . __('Hungarian Forint') ."', '', '', " . __('HUF', 'wpsc') . ", '0', '0', 'europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (43, '" . __('Hong Kong') ."', 'HK', '" . __('Hong Kong Dollar') ."', " . __('$', 'wpsc') . ", " . __('&#036;', 'wpsc') . ", " . __('HKD', 'wpsc') . ", '0', '0', 'asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (44, '" . __('Honduras') ."', 'HN', '" . __('Honduran Lempira') ."', '', '', " . __('HNL', 'wpsc') . ", '0', '0' , 'southamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (45, '" . __('Heard Island and McDonald Islands') ."', 'HM', '" . __('Australian Dollar') ."', " . __('$', 'wpsc') . ", " . __('&#036;', 'wpsc') . ", " . __('AUD', 'wpsc') . ", '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (46, '" . __('Haiti') ."', 'HT', '" . __('Haitian Gourde') ."', '', '', " . __('HTG', 'wpsc') . ", '0', '0', 'southamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (47, '" . __('Guyana') ."', 'GY', '" . __('Guyana Dollar') ."', " . __('$', 'wpsc') . ", " . __('&#036;', 'wpsc') . ", " . __('GYD', 'wpsc') . ", '0', '0', 'southamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (48, '" . __('Guinea Bissau') ."', 'GW', '" . __('Guinea-Bissau Peso') ."', '', '', " . __('GWP', 'wpsc') . ", '0', '0' ,'africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (49, '" . __('Guinea') ."', 'GN', '" . __('Guinea Franc') ."', '', '', " . __('GNF', 'wpsc') . ", '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (50, '" . __('Guernsey') ."', 'GF', '" . __('Pound Sterling') ."', " . __('£', 'wpsc') . ", " . __('&#163;', 'wpsc') . ", " . __('GBP', 'wpsc') . ", '0', '0' ,'europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (51, '" . __('Guatemala') ."', 'GT', '" . __('Guatemalan Quetzal') ."', '', '', " . __('QTQ', 'wpsc') . ", '0', '0', 'southamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (52, '" . __('Guam (USA)') ."', 'GU', '" . __('US Dollar') ."', " . __('$', 'wpsc') . ", " . __('&#036;', 'wpsc') . ", " . __('USD', 'wpsc') . ", '0', '0', 'asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (53, '" . __('Grenada') ."', 'GD', '" . __('East Carribean Dollar') ."', " . __('$', 'wpsc') . ", " . __('&#036;', 'wpsc') . ", " . __('XCD', 'wpsc') . ", '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (54, '" . __('Guadeloupe (French)') ."', 'GP', '" . __('Euro') ."', " . __('€', 'wpsc') . ", " . __('&#8364;', 'wpsc') . ", " . __('EUR', 'wpsc') . ", '0', '0', 'southamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (55, '" . __('Greenland') ."', 'GL', '" . __('Danish Krone') ."', '', '', " . __('DKK', 'wpsc') . ", '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (56, '" . __('Greece') ."', 'GR', '" . __('Euro') ."', " . __('€', 'wpsc') . ", " . __('&#8364;', 'wpsc') . ", " . __('EUR', 'wpsc') . ", '0', '19','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (57, '" . __('Gibraltar') ."', 'GI', '" . __('Gibraltar Pound') ."', '', '', " . __('GIP', 'wpsc') . ", '0', '0', 'europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (58, '" . __('Ghana') ."', 'GH', '" . __('Ghanaian Cedi') ."', '', '', " . __('GHC', 'wpsc') . ", '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (59, '" . __('Germany') ."', 'DE', '" . __('Euro') ."', " . __('€', 'wpsc') . ", " . __('&#8364;', 'wpsc') . ", " . __('EUR', 'wpsc') . ", '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (60, '" . __('Georgia') ."', 'GE', '" . __('Georgian Lari') ."', '', '', " . __('GEL', 'wpsc') . ", '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (61, '" . __('Gambia') ."', 'GM', '" . __('Gambian Dalasi') ."', '', '', " . __('GMD', 'wpsc') . ", '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (62, '" . __('Gabon') ."', 'GA', '" . __('CFA Franc BEAC') ."', '', '', " . __('XAF', 'wpsc') . ", '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (63, '" . __('French Southern Territories') ."', 'TF', '" . __('Euro') ."', " . __('€', 'wpsc') . ", " . __('&#8364;', 'wpsc') . ", " . __('EUR', 'wpsc') . ", '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (64, '" . __('France') ."', 'FR', '" . __('Euro') ."', " . __('€', 'wpsc') . ", " . __('&#8364;', 'wpsc') . ", " . __('EUR', 'wpsc') . ", '0', '0', 'europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (65, '" . __('Finland') ."', 'FI', '" . __('Euro') ."', " . __('€', 'wpsc') . ", " . __('&#8364;', 'wpsc') . ", " . __('EUR', 'wpsc') . ", '0', '0', 'europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (66, '" . __('Fiji') ."', 'FJ', '" . __('Fiji Dollar') ."', " . __('$', 'wpsc') . ", " . __('&#036;', 'wpsc') . ", " . __('FJD', 'wpsc') . ", '0', '0', 'asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (67, '" . __('Faroe Islands') ."', 'FO', '" . __('Danish Krone') ."', '', '', " . __('DKK', 'wpsc') . ", '0', '0' ,'europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (68, '" . __('Falkland Islands') ."', 'FK', '" . __('Falkland Islands Pound') ."', '', '', " . __('FKP', 'wpsc') . ", '0', '0' ,'southamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (69, '" . __('Ethiopia') ."', 'ET', '" . __('Ethiopian Birr') ."', '', '', " . __('ETB', 'wpsc') . ", '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (70, '" . __('Estonia') ."', 'EE', '" . __('Estonian Kroon') ."', '', '', " . __('EEK', 'wpsc') . ", '0', '0', 'europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (71, '" . __('Eritrea') ."', 'ER', '" . __('Eritrean Nakfa') ."', '', '', " . __('ERN', 'wpsc') . ", '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (72, '" . __('Equatorial Guinea') ."', 'GQ', '" . __('CFA Franc BEAC') ."', '', '', " . __('XAF', 'wpsc') . ", '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (73, '" . __('El Salvador') ."', 'SV', '" . __('El Salvador Colon') ."', '', '', " . __('SVC', 'wpsc') . ", '0', '0','southamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (74, '" . __('Egypt') ."', 'EG', '" . __('Egyptian Pound') ."', '', '', " . __('EGP', 'wpsc') . ", '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (75, '" . __('Ecuador') ."', 'EC', '" . __('Ecuador Sucre') ."', '', '', " . __('ECS', 'wpsc') . ", '0', '0','southamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (76, '" . __('East Timor') ."', 'TP', '" . __('Timor Escudo') ."', '', '', " . __('TPE', 'wpsc') . ", '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (77, '" . __('Dominican Republic') ."', 'DO', '" . __('Dominican Peso') ."', '', '', " . __('DOP', 'wpsc') . ", '0', '0','southamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (78, '" . __('Dominica') ."', 'DM', '" . __('East Caribbean Dollar') ."', " . __('$', 'wpsc') . ", " . __('&#036;', 'wpsc') . ", " . __('XCD', 'wpsc') . ", '0', '0','southamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (79, '" . __('Djibouti') ."', 'DJ', '" . __('Djibouti Franc') ."', '', '', " . __('DJF', 'wpsc') . ", '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (80, '" . __('Denmark') ."', 'DK', '" . __('Danish Krone') ."', '', '', " . __('DKK', 'wpsc') . ", '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (81, '" . __('Democratic Republic of Congo') ."', 'CD', '" . __('Francs') ."', '', '', " . __('CDF', 'wpsc') . ", '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (82, '" . __('Czech Rep.') ."', 'CZ', '" . __('Czech Koruna') ."', '', '', " . __('CZK', 'wpsc') . ", '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (83, '" . __('Cyprus') ."', 'CY', '" . __('Cyprus Pound') ."', '', '', " . __('CYP', 'wpsc') . ", '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (84, '" . __('Cuba') ."', 'CU', '" . __('Cuban Peso') ."', '', '', " . __('CUP', 'wpsc') . ", '0', '0','northamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (85, '" . __('Croatia') ."', 'HR', '" . __('Croatian Kuna') ."', '', '', " . __('HRK', 'wpsc') . ", '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (86, '" . __('Costa Rica') ."', 'CR', '" . __('Costa Rican Colon') ."', '', '', " . __('CRC', 'wpsc') . ", '0', '0','southamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (87, '" . __('Cook Islands') ."', 'CK', '" . __('New Zealand Dollar') ."', " . __('$', 'wpsc') . ", " . __('&#036;', 'wpsc') . ", " . __('NZD', 'wpsc') . ", '0', '0' ,'asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (88, '" . __('Congo') ."', 'CG', '" . __('CFA Franc BEAC') ."', '', '', " . __('XAF', 'wpsc') . ", '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (89, '" . __('Comoros') ."', 'KM', '" . __('Comoros Franc') ."', '', '', " . __('KMF', 'wpsc') . ", '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (90, '" . __('Colombia') ."', 'CO', '" . __('Colombian Peso') ."', '', '', " . __('COP', 'wpsc') . ", '0', '0','southamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (91, '" . __('Cocos (Keeling) Islands') ."', 'CC', '" . __('Australian Dollar') ."', " . __('$', 'wpsc') . ", " . __('&#036;', 'wpsc') . ", 'AUD', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (92, '" . __('Christmas Island') ."', 'CX', '" . __('Australian Dollar') ."', " . __('$', 'wpsc') . ", " . __('&#036;', 'wpsc') . ", " . __('AUD', 'wpsc') . ", '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (93, '" . __('Chile') ."', 'CL', '" . __('Chilean Peso') ."', '', '', " . __('CLP', 'wpsc') . ", '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (94, '" . __('China') ."', 'CN', '" . __('Yuan Renminbi') ."', '', '', " . __('CNY', 'wpsc') . ", '0', '0' ,'asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (95, '" . __('Chad') ."', 'TD', '" . __('CFA Franc BEAC') ."', '', '', " . __('XAF', 'wpsc') . ", '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (96, '" . __('Central African Republic') ."', 'CF', '" . __('CFA Franc BEAC') ."', '', '', " . __('XAF', 'wpsc') . ", '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (97, '" . __('Cayman Islands') ."', 'KY', '" . __('Cayman Islands Dollar') ."', " . __('$', 'wpsc') . ", " . __('&#036;', 'wpsc') . ", " . __('KYD', 'wpsc') . ", '0', '0','northamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (98, '" . __('Cape Verde') ."', 'CV', '" . __('Cape Verde Escudo') ."', '', '', " . __('CVE', 'wpsc') . ", '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (99, '" . __('Cameroon') ."', 'CM', '" . __('CFA Franc BEAC') ."', '', '', " . __('XAF', 'wpsc') . ", '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (100, '" . __('Canada') ."', 'CA', '" . __('Canadian Dollar') ."', " . __('$', 'wpsc') . ", " . __('&#036;', 'wpsc') . ", " . __('CAD', 'wpsc') . ", '1', '','northamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (101, '" . __('Cambodia') ."', 'KH', '" . __('Kampuchean Riel') ."', '', '', " . __('KHR', 'wpsc') . ", '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (102, '" . __('Burundi') ."', 'BI', '" . __('Burundi Franc') ."', '', '', " . __('BIF', 'wpsc') . ", '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (103, '" . __('Burkina Faso') ."', 'BF', '" . __('CFA Franc BCEAO') ."', '', '', " . __('XOF', 'wpsc') . ", '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (104, '" . __('Bulgaria') ."', 'BG', '" . __('Bulgarian Lev') ."', '', '', " . __('BGL', 'wpsc') . ", '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (105, '" . __('Brunei Darussalam') ."', 'BN', '" . __('Brunei Dollar') ."', " . __('$', 'wpsc') . ", " . __('&#036;', 'wpsc') . ", " . __('BND', 'wpsc') . ", '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (106, '" . __('British Indian Ocean Territory') ."', 'IO', '" . __('US Dollar') ."', '$', '&#036;', 'USD', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (107, '" . __('Brazil') ."', 'BR', '" . __('Brazilian Real') ."', '', '', " . __('BRL', 'wpsc') . ", '0', '0','southamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (108, '" . __('Bouvet Island') ."', 'BV', '" . __('Norwegian Krone') ."', '', '', " . __('NOK', 'wpsc') . ", '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (109, '" . __('Botswana') ."', 'BW', '" . __('Botswana Pula') ."', '', '', " . __('BWP', 'wpsc') . ", '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (110, '" . __('Bosnia-Herzegovina') ."', 'BA', '" . __('Marka') ."', '', '', " . __('BAM', 'wpsc') . ", '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (111, '" . __('Bolivia') ."', 'BO', '" . __('Boliviano') . "', '', '', " . __('BOB', 'wpsc') . ", '0', '0','southamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (112, '" . __('Bhutan') ."', 'BT', '" . __('Bhutan Ngultrum') . "', '', '', " . __('BTN', 'wpsc') . ", '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (113, '" . __('Bermuda') ."', 'BM', '" . __('Bermudian Dollar') . "', " . __('$', 'wpsc') . ", " . __('&#036;', 'wpsc') . ", " . __('BMD', 'wpsc') . ", '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (114, '" . __('Benin') ."', 'BJ', '" . __('CFA Franc BCEAO') . "', '', '', " . __('XOF', 'wpsc') . ", '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (115, '" . __('Belize') ."', 'BZ', '" . __('Belize Dollar') . "', " . __('$', 'wpsc') . ", " . __('&#036;', 'wpsc') . ", " . __('BZD', 'wpsc') . ", '0', '0','northamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (116, '" . __('Belgium') ."', 'BE', '" . __('Euro') . "', " . __('€', 'wpsc') . ", " . __('&#8364;', 'wpsc') . ", " . __('EUR', 'wpsc') . ", '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (117, '" . __('Belarus') ."', 'BY', '" . __('Belarussian Ruble') . "', '', '', " . __('BYB', 'wpsc') . ", '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (118, '" . __('Barbados') ."', 'BB', '" . __('Barbados Dollar') . "', " . __('$', 'wpsc') . ", " . __('&#036;', 'wpsc') . ", " . __('BBD', 'wpsc') . ", '0', '0','southamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (119, '" . __('Bangladesh') ."', 'BD', '" . __('Bangladeshi Taka') . "', '', '', " . __('BDT', 'wpsc') . ", '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (120, '" . __('Bahrain') ."', 'BH', '" . __('Bahraini Dinar') . "', '', '', " . __('BHD', 'wpsc') . ", '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (121, '" . __('Bahamas') ."', 'BS', '" . __('Bahamian Dollar') . "', " . __('$', 'wpsc') . ", " . __('&#036;', 'wpsc') . ", " . __('BSD', 'wpsc') . ", '0', '0','northamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (122, '" . __('Azerbaijan') ."', 'AZ', '" . __('Azerbaijanian Manat') . "', '', '', " . __('AZM', 'wpsc') . ", '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (123, '" . __('Austria') ."', 'AT', '" . __('Euro') . "', " . __('€', 'wpsc') . ", " . __('&#8364;', 'wpsc') . ", " . __('EUR', 'wpsc') . ", '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (124, '" . __('Aruba') ."', 'AW', '" . __('Aruban Guilder') . "', '', '', " . __('AWG', 'wpsc') . ", '0', '0','southamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (125, '" . __('Armenia') ."', 'AM', '" . __('Armenian Dram') . "', '', '', " . __('AMD', 'wpsc') . ", '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (126, '" . __('Argentina') ."', 'AR', '" . __('Argentine Peso') . "', '', '', " . __('ARS', 'wpsc') . ", '0', '0','southamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (127, '" . __('Antigua and Barbuda') ."', 'AG', '" . __('East Caribbean Dollar') . "', " . __('$', 'wpsc') . ", " . __('&#036;', 'wpsc') . ", " . __('XCD', 'wpsc') . ", '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (128, '" . __('Antarctica') ."', 'AQ', '" . __('Dollar') . "', " . __('$', 'wpsc') . ", " . __('&#036;', 'wpsc') . ", " . __('ATA', 'wpsc') . ", '0', '0','antarctica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (129, '" . __('Anguilla') ."', 'AI', '" . __('East Caribbean Dollar') . "', " . __('$', 'wpsc') . ", " . __('&#036;', 'wpsc') . ", " . __('XCD', 'wpsc') . ", '0', '0','northamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (130, '" . __('Angola') ."', 'AO', '" . __('Angolan New Kwanza') . "', '', '', " . __('AON', 'wpsc') . ", '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (131, '" . __('Andorra') ."', 'AD', '" . __('Euro') . "', " . __('€', 'wpsc') . ", " . __('&#8364;', 'wpsc') . ", " . __('EUR', 'wpsc') . ", '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (132, '" . __('American Samoa') ."', 'AS', '" . __('US Dollar') . "', " . __('$', 'wpsc') . ", " . __('&#036;', 'wpsc') . ", " . __('USD', 'wpsc') . ", '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (133, '" . __('Algeria') ."', 'DZ', '" . __('Algerian Dinar') . "', '', '', " . __('DZD', 'wpsc') . ", '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (134, '" . __('Albania') ."', 'AL', '" . __('Albanian Lek') . "', '', '', " . __('ALL', 'wpsc') . ", '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (135, '" . __('Afghanistan') ."', 'AF', '" . __('Afghanistan Afghani') . "', '', '', " . __('AFA', 'wpsc') . ", '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (136, '" . __('USA') ."', 'US', '" . __('US Dollar') . "', " . __('$', 'wpsc') . ", " . __('&#036;', 'wpsc') . ", " . __('USD', 'wpsc') . ", '1', '','northamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (137, '" . __('Australia') ."', 'AU', '" . __('Australian Dollar') . "', " . __('$', 'wpsc') . ", " . __('&#036;', 'wpsc') . ", " . __('AUD', 'wpsc') . ", '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (138, '" . __('Great Britain') ."', 'GB', '" . __('Pound Sterling') . "', " . __('£', 'wpsc') . ", " . __('&#163;', 'wpsc') . ", " . __('GBP', 'wpsc') . ", '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (139, '" . __('Mauritius') ."', 'MU', '" . __('Mauritius Rupee') . "', '', '', " . __('MUR', 'wpsc') . ", '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (140, '" . __('Mayotte') ."', 'YT', '" . __('Euro') . "', " . __('€', 'wpsc') . ", " . __('&#8364;', 'wpsc') . ", " . __('EUR', 'wpsc') . ", '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (141, '" . __('Mexico') ."', 'MX', '" . __('Mexican Nuevo Peso') . "', '', '', " . __('MXN', 'wpsc') . ", '0', '0','northamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (142, '" . __('Micronesia') ."', 'FM', '" . __('US Dollar') . "', " . __('$', 'wpsc') . ", " . __('&#036;', 'wpsc') . ", " . __('USD', 'wpsc') . ", '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (143, '" . __('Moldova') ."', 'MD', '" . __('Moldovan Leu') . "', '', '', " . __('MDL', 'wpsc') . ", '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (144, '" . __('Monaco') ."', 'MC', '" . __('Euro') . "', " . __('€', 'wpsc') . ", " . __('&#8364;', 'wpsc') . ", " . __('EUR', 'wpsc') . ", '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (145, '" . __('Mongolia') ."', 'MN', '" . __('Mongolian Tugrik') . "', '', '', " . __('MNT', 'wpsc') . ", '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (146, '" . __('Montserrat') ."', 'MS', '" . __('East Caribbean Dollar') . "', " . __('$', 'wpsc') . ", " . __('&#036;', 'wpsc') . ", " . __('XCD', 'wpsc') . ", '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (147, '" . __('Morocco') ."', 'MA', '" . __('Moroccan Dirham') . "', '', '', " . __('MAD', 'wpsc') . ", '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (148, '" . __('Mozambique') ."', 'MZ', '" . __('Mozambique Metical') . "', '', '', " . __('MZM', 'wpsc') . ", '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (149, '" . __('Myanmar') ."', 'MM', '" . __('Myanmar Kyat') . "', '', '', " . __('MMK', 'wpsc') . ", '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (150, '" . __('Namibia') ."', 'NA', '" . __('Namibian Dollar') . "', " . __('$', 'wpsc') . ", " . __('&#036;', 'wpsc') . ", " . __('NAD', 'wpsc') . ", '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (151, '" . __('Nauru') ."', 'NR', '" . __('Australian Dollar') . "', " . __('$', 'wpsc') . ", " . __('&#036;', 'wpsc') . ", " . __('AUD', 'wpsc') . ", '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (152, '" . __('Nepal') ."', 'NP', '" . __('Nepalese Rupee') . "', '', '', " . __('NPR', 'wpsc') . ", '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (153, '" . __('Netherlands') ."', 'NL', '" . __('Euro') . "', " . __('€', 'wpsc') . ", " . __('&#8364;', 'wpsc') . ", " . __('EUR', 'wpsc') . ", '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (154, '" . __('Netherlands Antilles') ."', 'AN', '" . __('Netherlands Antillean Guilder') . "', '', '', " . __('ANG', 'wpsc') . ", '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (155, '" . __('New Caledonia (French)') ."', 'NC', '" . __('CFP Franc') . "', '', '', 'XPF', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (156, '" . __('New Zealand') ."', 'NZ', '" . __('New Zealand Dollar') . "', '$', '&#036;', 'NZD', '0', '12.5','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (157, '" . __('Nicaragua') ."', 'NI', '" . __('Nicaraguan Cordoba Oro') . "', '', '', 'NIC', '0', '0','northamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (158, '" . __('Niger') ."', 'NE', '" . __('CFA Franc BCEAO') . "', '', '', 'XOF', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (159, '" . __('Nigeria') ."', 'NG', '" . __('Nigerian Naira') . "', '', '', 'NGN', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (160, '" . __('Niue') ."', 'NU', '" . __('New Zealand Dollar') . "', '$', '&#036;', 'NZD', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (161, '" . __('Norfolk Island') ."', 'NF', '" . __('Australian Dollar') . "', '$', '&#036;', 'AUD', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (162, '" . __('Northern Mariana Islands') ."', 'MP', '" . __('US Dollar') . "', '$', '&#036;', 'USD', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (163, '" . __('Norway') ."', 'NO', '" . __('Norwegian Krone') . "', '', '', 'NOK', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (164, '" . __('Oman') ."', 'OM', '" . __('Omani Rial') . "', '', '', 'OMR', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (165, '" . __('Pakistan') ."', 'PK', '" . __('Pakistan Rupee') . "', '', '', 'PKR', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (166, '" . __('Palau') ."', 'PW', '" . __('US Dollar') . "', '$', '&#036;', 'USD', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (167, '" . __('Panama') ."', 'PA', '" . __('Panamanian Balboa') . "', '', '', 'PAB', '0', '0','southamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (168, '" . __('Papua New Guinea') ."', 'PG', '" . __('Papua New Guinea Kina') . "', '', '', 'PGK', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (169, '" . __('Paraguay') ."', 'PY', '" . __('Paraguay Guarani') . "', '', '', 'PYG', '0', '0','southamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (170, '" . __('Peru') ."', 'PE', '" . __('Peruvian Nuevo Sol') . "', '', '', 'PEN', '0', '0','southamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (171, '" . __('Philippines') ."', 'PH', '" . __('Philippine Peso') . "', '', '', 'PHP', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (172, '" . __('Pitcairn Island') ."', 'PN', '" . __('New Zealand Dollar') . "', '$', '&#036;', 'NZD', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (173, '" . __('Poland') ."', 'PL', '" . __('Polish Zloty') . "', '', '', 'PLN', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (174, '" . __('Polynesia (French)') ."', 'PF', '" . __('CFP Franc') . "', '', '', 'XPF', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (175, '" . __('Portugal') ."', 'PT', '" . __('Euro') . "', '€', '&#8364;', 'EUR', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (176, '" . __('Puerto Rico') ."', 'PR', '" . __('US Dollar') . "', '$', '&#036;', 'USD', '0', '0','northamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (177, '" . __('Qatar') ."', 'QA', '" . __('Qatari Rial') . "', '', '', 'QAR', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (178, '" . __('Reunion (French)') ."', 'RE', '" . __('Euro') . "', '€', '&#8364;', 'EUR', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (179, '" . __('Romania') ."', 'RO', '" . __('Romanian Leu') . "', '', '', 'RON', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (180, '" . __('Russia') ."', 'RU', '" . __('Russian Ruble') . "', '', '', 'RUR', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (181, '" . __('Rwanda') ."', 'RW', '" . __('Rwanda Franc') . "', '', '', 'RWF', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (182, '" . __('Saint Helena') ."', 'SH', '" . __('St. Helena Pound') . "', '', '', 'SHP', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (183, '" . __('Saint Kitts & Nevis Anguilla') ."', 'KN', '" . __('East Caribbean Dollar') . "', '$', '&#036;', 'XCD', '0', '0','northamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (184, '" . __('Saint Lucia') ."', 'LC', '" . __('East Caribbean Dollar') . "', '$', '&#036;', 'XCD', '0', '0','northamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (185, '" . __('Saint Pierre and Miquelon') ."', 'PM', '" . __('Euro') . "', '€', '&#8364;', 'EUR', '0', '0','northamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (186, '" . __('Saint Vincent & Grenadines') ."', 'VC', '" . __('East Caribbean Dollar') . "', '$', '&#036;', 'XCD', '0', '0','northamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (187, '" . __('Samoa') ."', 'WS', '" . __('Samoan Tala') . "', '', '', 'WST', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (188, '" . __('San Marino') ."', 'SM', '" . __('Italian Lira') . "', '', '', 'ITL', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (189, '" . __('Sao Tome and Principe') ."', 'ST', '" . __('Dobra') . "', '', '', 'STD', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (190, '" . __('Saudi Arabia') ."', 'SA', '" . __('Saudi Riyal') . "', '', '', 'SAR', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (191, '" . __('Senegal') ."', 'SN', '" . __('CFA Franc BCEAO') . "', '', '', 'XOF', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (192, '" . __('Seychelles') ."', 'SC', '" . __('Seychelles Rupee') . "', '', '', 'SCR', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (193, '" . __('Sierra Leone') ."', 'SL', '" . __('Sierra Leone Leone') . "', '', '', 'SLL', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (194, '" . __('Singapore') ."', 'SG', '" . __('Singapore Dollar') . "', '$', '&#036;', 'SGD', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (195, '" . __('Slovakia') ."', 'SK', '" . __('Euro') . "', '€', '&#8364;', 'EUR', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (196, '" . __('Slovenia') ."', 'SI', '" . __('Slovenian Tolar') . "', '', '', 'SIT', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (197, '" . __('Solomon Islands') ."', 'SB', '" . __('Solomon Islands Dollar') . "', '$', '&#036;', 'SBD', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (198, '" . __('Somalia') ."', 'SO', '" . __('Somali Shilling') . "', '', '', 'SOD', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (199, '" . __('South Africa') ."', 'ZA', '" . __('South African Rand') . "', '', '', 'ZAR', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (200, '" . __('South Georgia & South Sandwich Islands') ."', 'GS', '" . __('Pound Sterling') . "', '£', '&#163;', 'GBP', '0', '0','southamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (201, '" . __('Spain') ."', 'ES', '" . __('Euro') . "', '€', '&#8364;', 'EUR', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (202, '" . __('Sri Lanka') ."', 'LK', '" . __('Sri Lanka Rupee') . "', '', '', 'LKR', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (203, '" . __('Sudan') ."', 'SD', '" . __('Sudanese Dinar') . "', '', '', 'SDD', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (204, '" . __('Suriname') ."', 'SR', '" . __('Surinam Guilder') . "', '', '', 'SRG', '0', '0','southamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (205, '" . __('Svalbard and Jan Mayen Islands') ."', 'SJ', '" . __('Norwegian Krone') . "', '', '', 'NOK', '0', '0','','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (206, '" . __('Swaziland') ."', 'SZ', '" . __('Swaziland Lilangeni') . "', '', '', 'SZL', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (207, '" . __('Sweden') ."', 'SE', '" . __('Swedish Krona') . "', '', '', 'SEK', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (208, '" . __('Switzerland') ."', 'CH', '" . __('Swiss Franc') . "', '', '', 'CHF', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (209, '" . __('Syria') ."', 'SY', '" . __('Syrian Pound') . "', '', '', 'SYP', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (210, '" . __('Taiwan') ."', 'TW', '" . __('Taiwan Dollar') . "', '$', '&#036;', 'TWD', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (211, '" . __('Tajikistan') ."', 'TJ', '" . __('Tajik Ruble') . "', '', '', 'TJR', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (212, '" . __('Tanzania') ."', 'TZ', '" . __('Tanzanian Shilling') . "', '', '', 'TZS', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (213, '" . __('Thailand') ."', 'TH', '" . __('Thai Baht') . "', '', '', 'THB', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (214, '" . __('Togo') ."', 'TG', '" . __('CFA Franc BCEAO') . "', '', '', 'XOF', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (215, '" . __('Tokelau') ."', 'TK', '" . __('New Zealand Dollar') . "', '$', '&#036;', 'NZD', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (216, '" . __('Tonga') ."', 'TO', '" . __('Tongan Pa&#699;anga') . "', '', '', 'TOP', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (217, '" . __('Trinidad and Tobago') ."', 'TT', '" . __('Trinidad and Tobago Dollar') . "', '$', '&#036;', 'TTD', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (218, '" . __('Tunisia') ."', 'TN', '" . __('Tunisian Dollar') . "', '$', '&#036;', 'TND', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (219, '" . __('Turkey') ."', 'TR', '" . __('Turkish Lira') . "', '', '', 'TRL', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (220, '" . __('Turkmenistan') ."', 'TM', '" . __('Manat') . "', '', '', 'TMM', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (221, '" . __('Turks and Caicos Islands') ."', 'TC', '" . __('US Dollar') . "', '$', '&#036;', 'USD', '0', '0', 'northamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (222, '" . __('Tuvalu') ."', 'TV', '" . __('Australian Dollar') . "', '$', '&#036;', 'AUD', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (223, '" . __('U.K.') ."', 'UK', '" . __('Pound Sterling') . "', '£', '&#163;', 'GBP', '0', '17.5','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (224, '" . __('Uganda') ."', 'UG', '" . __('Uganda Shilling') . "', '', '', 'UGS', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (225, '" . __('Ukraine') ."', 'UA', '" . __('Ukraine Hryvnia') . "', '', '', 'UAG', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (226, '" . __('United Arab Emirates') ."', 'AE', '" . __('Arab Emirates Dirham') . "', '', '', 'AED', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (227, '" . __('Uruguay') ."', 'UY', '" . __('Uruguayan Peso') . "', '', '', 'UYP', '0', '0','southamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (228, '" . __('USA Minor Outlying Islands') ."', 'UM', '" . __('US Dollar') . "', '$', '&#036;', 'USD', '0', '0','','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (229, '" . __('Uzbekistan') ."', 'UZ', '" . __('Uzbekistan Sum') . "', '', '', 'UZS', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (230, '" . __('Vanuatu') ."', 'VU', '" . __('Vanuatu Vatu') . "', '', '', 'VUV', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (231, '" . __('Vatican') ."', 'VA', '" . __('Euro') . "', '€', '&#8364;', 'EUR', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (232, '" . __('Venezuela') ."', 'VE', '" . __('Venezuelan Bolivar') . "', '', '', 'VUB', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (233, '" . __('Vietnam') ."', 'VN', '" . __('Vietnamese Dong') . "', '', '', 'VND', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (234, '" . __('Virgin Islands (British)') ."', 'VG', '" . __('US Dollar') . "', '$', '&#036;', 'USD', '0', '0','northamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (235, '" . __('Virgin Islands (USA)') ."', 'VI', '" . __('US Dollar') . "', '$', '&#036;', 'USD', '0', '0','northamerica','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (236, '" . __('Wallis and Futuna Islands') ."', 'WF', '" . __('CFP Franc') . "', '', '', 'XPF', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (237, '" . __('Western Sahara') ."', 'EH', '" . __('Moroccan Dirham') . "', '', '', 'MAD', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (238, '" . __('Yemen') ."', 'YE', '" . __('Yemeni Rial') . "', '', '', 'YER', '0', '0','asiapacific','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (239, '" . __('Yugoslavia') ."', 'YU', '" . __('Yugoslav New Dinar') . "', '', '', 'YUN', '0', '0','europe','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (240, '" . __('Zambia') ."', 'ZM', '" . __('Zambian Kwacha') . "', '', '', 'ZMK', '0', '0','africa','1');
INSERT INTO `".WPSC_TABLE_CURRENCY_LIST."` VALUES (241, '" . __('Zimbabwe') ."', 'ZW', '" . __('Zimbabwe Dollar') . "', '$', '&#036;', 'ZWD', '0', '0','africa','1');"; ?>